version: "3"
services:
    worker:
        container_name: "kamori-worker"
        build:
            context: .
        volumes:
            - worker:/data
        stop_signal: SIGINT
        restart: unless-stopped
        command: "python -m kamori"
        ports:
            - "${EXTERNAL_PORT:-8080}:8080"

volumes:
    worker:
